---
- name: create vsftpd users
  shell: |
    /usr/bin/docker exec {{ vsftpd_container_name }} \
    /add-vsftpd-user.sh "{{ item.username }}" \
                        '{{ item.password }}' \
                        "{{ item.uid }}"
  register: created_user
  changed_when: created_user.stdout | length > 0
  with_items: "{{ vsftpd_users }}"
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Create user home directory
  file:
    path: "{{ vsftpd_home_volume }}/{{ item.username }}"
    state: directory
    owner: "{{ item.uid }}"
    group: "{{ item.uid }}"
    mode: 0755
  with_items: "{{ vsftpd_users }}"
