---
- name: Determine if vsftpd user exist
  shell: |
    set -o pipefail
    cat {{ vsftpd_config_path }}/passwd \
    | grep {{ item.username }}:x:{{ item.uid }}
  args:
    executable: /bin/bash
  register: user_exists
  changed_when: user_exists.stdout | length < 1
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
  failed_when: false

- name: determine users for creation
  set_fact:
    users_for_creation: "{{ users_for_creation + [item] }}"
  when: user_exists.changed  # noqa 503
