---
- name: Create vsftpd directory
  file:
    path: "{{ vsftpd_volumes_path }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create config directory
  file:
    path: "{{ vsftpd_config_path }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create ftp root directory
  file:
    path: "{{ vsftpd_home_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create ftp volume
  file:
    path: "{{ vsftpd_ftp_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0555

- name: Create ftp/incomming volume
  file:
    path: "{{ vsftpd_incomming_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0777
