---
- name: Update vsftpd user password
  shell: |
    /usr/bin/docker exec {{ vsftpd_container_name }} \
      /update-vsftpd-user-password.sh "{{ item.username }}" \
                                      '{{ item.password }}'
  register: update_password
  changed_when: update_password.stdout | length > 0
