---
- name: Restart vsftpd service
  systemd:
    name: "{{ vsftpd_service_name }}"
    state: restarted
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
