---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should create vsftpd config
      stat:
        path: /srv/vsftpd/config/vsftpd.conf
        checksum_algorithm: sha256
      register: vsftpd_config_file
      failed_when: not (
        vsftpd_config_file.stat.exists
        )

    - name: Should template Dockerfile
      stat:
        path: /opt/vsftpd/docker/Dockerfile
        checksum_algorithm: sha256
      register: docker_file
      failed_when: not (
        docker_file.stat.exists
        )

    - name: Should open 20/tcp port
      command: nc -z -w1 localhost 20
      register: netcat_20
      retries: 300
      delay: 1
      until: netcat_20 is defined
        and netcat_20.rc == 0

    - name: Should open 21/tcp port
      command: nc -z -w1 localhost 21
      register: netcat_21
      retries: 300
      delay: 1
      until: netcat_21 is defined
        and netcat_21.rc == 0
