---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should create vsftpd config
      stat:
        path: /srv/vsftpd/config/vsftpd/vsftpd.conf
        checksum_algorithm: sha256
      register: vsftpd_config_file
      failed_when: not (
        vsftpd_config_file.stat.exists
        )

    - name: Should create vsftpd userlist file
      stat:
        path: /srv/vsftpd/config/vsftpd/vsftpd.user_list
        checksum_algorithm: sha256
      register: vsftpd_userlist_file
      failed_when: not (
        vsftpd_userlist_file.stat.exists
        )

    - name: Should create etc/passwd db file
      stat:
        path: /srv/vsftpd/config/etc/passwd
        checksum_algorithm: sha256
      register: etc_passwd_file
      failed_when: not (
        etc_passwd_file.stat.exists
        )

    - name: Should create etc/group db file
      stat:
        path: /srv/vsftpd/config/etc/group
        checksum_algorithm: sha256
      register: etc_group_file
      failed_when: not (
        etc_group_file.stat.exists
        )

    - name: Should create etc/shadow db file
      stat:
        path: /srv/vsftpd/config/etc/shadow
        checksum_algorithm: sha256
      register: etc_shadow_file
      failed_when: not (
        etc_shadow_file.stat.exists
        )

    - name: Should template Dockerfile
      stat:
        path: /opt/vsftpd/docker/Dockerfile
        checksum_algorithm: sha256
      register: docker_file
      failed_when: not (
        docker_file.stat.exists
        )

  post_tasks:
    - name: Delete built docker image
      docker_image:
        name: local/vsftpd:latest
        state: absent
      failed_when: false
