{% if vsftpd_centos_version is not defined or vsftpd_centos_version == 'latest' %}
FROM centos:latest
{% else %}
FROM centos:{{ vsftpd_centos_version }}
{% endif %}

MAINTAINER borisskert <boris.skert@gmail.com>

RUN yum -y update && \
    yum clean all && \
    yum install -y \
{% if vsftpd_package_version is defined and vsftpd_package_version != 'latest' %}
      vsftpd-{{ vsftpd_package_version }} && \
{% else %}
      vsftpd && \
{% endif %}
    yum clean all

COPY add-vsftpd-user.sh /add-vsftpd-user.sh
COPY update-vsftpd-user-password.sh /update-vsftpd-user-password.shd

VOLUME ["/etc/vsftpd", "/var/log", "/home"]

EXPOSE 20 21

ENTRYPOINT ["/usr/sbin/vsftpd", "/etc/vsftpd/vsftpd.conf"]
